export const transactionList = [
  {
    date: "Thu, 15 Feb 2024",
    transactions: [
      {
        time: "10:41 AM",
        type: "debit",
        amount: "- ₹50,009.44",
        contact: "Vijay",
        paymentMethod: "NEFT",
        source: "NEFT",
        payoutPurpose: null,
        payout: null,
        bankTransfer: null,
        utr: null,
        closingBalance: "₹1,00,00,000.00",
        via: "NEFT",
      },
      {
        time: "10:40 AM",
        type: "debit",
        amount: "- ₹12,004.72",
        contact: "Bahadur",
        paymentMethod: null,
        source: "IMPS",
        payoutPurpose: null,
        payout: null,
        bankTransfer: null,
        utr: "Nb2EdgVEjqxZZO",
        closingBalance: "₹99,87,995.28",
        via: "IMPS",
      },
      {
        time: "10:40 AM",
        type: "debit",
        amount: "- ₹10,004.72",
        contact: "Random Verma",
        paymentMethod: null,
        source: "IMPS",
        payoutPurpose: null,
        payout: null,
        bankTransfer: null,
        utr: "Nb2FCQm50qdJGb",
        closingBalance: "₹99,77,990.56",
        via: "IMPS",
      },
      {
        time: "10:40 AM",
        type: "debit",
        amount: "- ₹10,004.72",
        contact: "Shivam Arora",
        paymentMethod: null,
        source: "IMPS",
        payoutPurpose: null,
        payout: null,
        bankTransfer: null,
        utr: null,
        closingBalance: "₹99,67,985.84",
        via: "IMPS",
      },
      {
        time: "10:40 AM",
        type: "debit",
        amount: "- ₹10,004.72",
        contact: "Ujjwal",
        paymentMethod: "RazorpayX Lite",
        source: null,
        payoutPurpose: null,
        payout: null,
        bankTransfer: null,
        utr: null,
        closingBalance: "₹99,57,981.12",
        via: "RazorpayX Lite",
      },
      {
        time: "10:40 AM",
        type: "credit",
        amount: "+ ₹1,00,00,000.00",
        contact: "Amit Kumar",
        paymentMethod: null,
        source: null,
        payoutPurpose: "Automate Accounting",
        payout: null,
        bankTransfer: null,
        utr: null,
        closingBalance: "₹1,00,00,000.00",
        via: "NEFT",
      },
      {
        time: "10:40 AM",
        type: "credit",
        amount: "+ ₹44,009.44",
        contact: "Ujjwal",
        paymentMethod: null,
        source: null,
        payoutPurpose: null,
        payout: null,
        bankTransfer: null,
        utr: null,
        closingBalance: "₹1,00,44,009.44",
        via: "Bank Deposit",
      },
      {
        time: "11:00 AM",
        type: "credit",
        amount: "+ ₹25,000.00",
        contact: "John Doe",
        paymentMethod: null,
        source: null,
        payoutPurpose: "Refund",
        payout: null,
        bankTransfer: null,
        utr: null,
        closingBalance: "₹1,00,69,009.44",
        via: "Bank Transfer",
      },
      {
        time: "11:15 AM",
        type: "debit",
        amount: "- ₹5,000.50",
        contact: "Alice",
        paymentMethod: "Credit Card",
        source: null,
        payoutPurpose: null,
        payout: null,
        bankTransfer: null,
        utr: null,
        closingBalance: "₹1,00,64,008.94",
        via: "Online Purchase",
      },
      {
        time: "11:30 AM",
        type: "debit",
        amount: "- ₹8,500.75",
        contact: "Bob",
        paymentMethod: "PayPal",
        source: null,
        payoutPurpose: null,
        payout: null,
        bankTransfer: null,
        utr: "Nb2XYZ123",
        closingBalance: "₹1,00,55,508.19",
        via: "Online Transfer",
      },
      {
        time: "12:00 PM",
        type: "credit",
        amount: "+ ₹15,000.00",
        contact: "Eva",
        paymentMethod: null,
        source: null,
        payoutPurpose: "Gift",
        payout: null,
        bankTransfer: null,
        utr: null,
        closingBalance: "₹1,00,70,508.19",
        via: "Cash Deposit",
      },
    ],
  },
];
